spring:
  application:
    name: PartWorkBack
  datasource:
    url: jdbc:mysql://localhost:3306/campus_parttime
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      add-mappings: false

server:
  port: 8080

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true


jwt:
  secret: "mySuperSecureSecretKeyThatIsLongEnoughForHS512AlgorithmWhichRequires512Bits!!" # 长度>=32
  expiration: 3600000

# 自定义应用配置
app:
  upload:
    base-dir: ./uploads/